### ISSUE TITLE
拷贝2个文件后,potplayer无法识别到.窗口报错

### ISSUE THREAD

**Issue by killtime1215** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#10]
--
作者你好,感谢提供优秀作品.
我按照教程操作,拷贝2个文件后,potplayer报错弹窗.
错误窗口内容:
--------PotPlayer's AngelScript console--------
SubtitleTranslate - baidu.as (7, 1) : ERR  : Unexpected token '<'
SubtitleTranslate - baidu.as (318, 242) : ERR  : Unexpected token '<multiline string constant>'
----------
麻烦可以帮忙看看吗?谢谢

**Comment by fjqingyou** [comment]
请问有改动过代码吗？正常复制的文件一般应该不会出现这个问题才对

**Comment by fjqingyou** [comment]
应该是代码内容被改动的问题。。SubtitleTranslate - baidu.as 原始文件 总共才 279 行。但是报错信息却提示 318, 242 足足318行。。请重新复制 SubtitleTranslate - baidu.as 文件测试

**Comment by killtime1215** [comment]
感谢,听你这么一说好像是文件没有下载正确.

**Comment by fjqingyou** [comment]
长时间无回复关闭此问题，若问题还存在，可随时重新打开它！
