### ISSUE TITLE
能否实现保存翻译的字幕？

### ISSUE THREAD

**Issue by lga2011** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#11]
因为看教程有可能一个视频会看几次，如果能保存翻译后的中文字幕，是不是可以节省一下百度的额度？

**Comment by fjqingyou** [comment]
这是一个很好的想法，今晚想到了个解决方案，近期处理！

**Comment by fjqingyou** [comment]
想到的解决方案遇到了问题。暂时没能在PotPlayer提供的API中找到合适的写入文件的方法。

**Comment by DeltaG501** [comment]
确实这个场景挺实用的，比如给小白朋友发自动翻译好的srt就行，不用教ta注册拿api

**Comment by Askwind** [comment]
不知道这个功能近期会更新吗？

**Comment by fjqingyou** [comment]
详细看了下，当前对接的方式已经是完全免费模式对接的，所以貌似没必要这个功能了！

**Comment by fjqingyou** [comment]
而如果是是要翻译保存文件。PotPlayer没提供翻译的字幕源文件信息，难以再次保存新的文件，如果是要翻译后发别人的话，恐怕直接用网页翻译方式复制粘贴更简单些！
