### ISSUE TITLE
打开potplayer后报错

### ISSUE THREAD

**Issue by mouzui** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#12]
![image](https://user-images.githubusercontent.com/49224591/80939309-d4da8b00-8e0e-11ea-944a-ded172c9c397.png)

**Comment by fjqingyou** [comment]
你好。请确认下 SubtitleTranslate - baidu.as 这个文件是否是完整的。。。可以在当前git里面找到这个文件。。看看文件开始部分。和文件末尾部分。。是否安装到 potplayer 里面的文件是否一致

**Comment by mouzui** [comment]
> 你好。请确认下 SubtitleTranslate - baidu.as 这个文件是否是完整的。。。可以在当前git里面找到这个文件。。看看文件开始部分。和文件末尾部分。。是否安装到 potplayer 里面的文件是否一致

谢谢您的帮助，已经解决。
