### ISSUE TITLE
中英文混合字幕，如何不看到英文字幕，只看到完整的中文字幕呢？

### ISSUE THREAD

**Issue by leftchest** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#13]
设置总是使用，只显示翻译
中文字幕直接被屏蔽了
中英文混合字幕
原中文字幕无法显示，只显示原英文字幕的中文翻译，结果就是呈现的字幕不完整

经测试，想呈现完整的中文字幕，只有设置总是使用，翻译在下或者在上

所以反馈的问题是：中英文混合字幕，如何不看到英文字幕，只看到完整的中文字幕呢？

**Comment by fjqingyou** [comment]
抱歉呐！这个暂时没有一个较好的解决方案！

**Comment by leftchest** [comment]
> 抱歉呐！这个暂时没有一个较好的解决方案！

已经提供了很大便利，非常感谢！！
