### ISSUE TITLE
想请问一下，potplayer插件开发哪里有相关文档或教程吗？

### ISSUE THREAD

**Issue by JoJenH** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#14]
因为个人想实现一个搜索字幕关键字跳转到相关位置播放的功能，但是不想从头开发一个播放器，所以想基于potplayer二次开发，但是现在完全没有任何关于插件开发的头绪，甚至连使用什么语言都不知道。还请麻烦看到后告知一下哈哈，提前谢过。

**Comment by fjqingyou** [comment]
额。我只是看了公开API部分。以及api中提到的脚本网站瞅了下语法罢了。并没有找到其他的东东。这个建议直接去播放器的官方反馈比较合适！

**Comment by ma5d** [comment]
> 额。我只是看了公开API部分。以及api中提到的脚本网站瞅了下语法罢了。并没有找到其他的东东。这个建议直接去播放器的官方反馈比较合适！

给我看看，我也想看看语法

**Comment by fjqingyou** [comment]
@horse-world PotPlayer 安装目录下的 Extension 文件夹里面有个 api.txt 文件。它的首行内容就是
```
Script engine is AngelScript(http://www.angelcode.com/angelscript/)
```
再后续的内容是 PotPlayer 提供的 API 声明
