### ISSUE TITLE
外挂字幕测试正常，但在线翻译不出

### ISSUE THREAD

**Issue by awksed** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#16]
百度控制台显示0请求，视频不显示任何字幕。
APP ID和秘钥已填入。
点“测试”按钮显示一个只有叉号图标没有文字的弹窗。
请问是什么情况？
先谢。

**Comment by awksed** [comment]
不好意思，我理解错了这个代码的功能。
1是我为了屏蔽potplayer升级，用防火墙拦截了它联网。
2是我以为这个代码是能从音频中生成字幕，这点我理解错了，这个代码是从外挂字幕中翻译的，理解错了抱歉。

**Comment by fjqingyou** [comment]
OK

**Comment by James-dai** [comment]
我也以为是直接可以从音频中生成字幕。
