### ISSUE TITLE
无法翻译，测试报错

### ISSUE THREAD

**Issue by BrightHsu** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#17]
作者你好！
我这边翻译不了，测试结果如图所示
![01](https://user-images.githubusercontent.com/30190764/93021621-29401380-f616-11ea-96b7-09db5b11c39c.png)
![02](https://user-images.githubusercontent.com/30190764/93021625-2c3b0400-f616-11ea-8954-8994fbdfc08e.png)

有时间请帮我看看，感谢！

**Comment by fjqingyou** [comment]
看下方的控制台。似乎是代码执行超时了。怀疑是网络连接超时了？是不是禁止了potplayer联网了？？

**Comment by BrightHsu** [comment]
这就是我很纳闷的一点，设置  允许应用通过防火墙了没反应，多测试两次，软件就崩了

**Comment by rumosky** [comment]
设置完成之后没作用，PotPlayer版本：201021(1.7.21311)，APPid和密钥也没问题，设置也没问题，但是就是没作用。

**Comment by rumosky** [comment]
![QQ截图20201121212332](https://user-images.githubusercontent.com/41993388/99878373-e31fb580-2c3f-11eb-9cfe-a1ce62493ab9.png)
上图是测试的结果，应该也是没问题的

**Comment by fjqingyou** [comment]
> ![QQ截图20201121212332](https://user-images.githubusercontent.com/41993388/99878373-e31fb580-2c3f-11eb-9cfe-a1ce62493ab9.png)
> 上图是测试的结果，应该也是没问题的

如果是这个的话，很可能是视频本身是硬画在帧上面的。无法读取字幕文本，所以无法翻译！

**Comment by rumosky** [comment]
@fjqingyou 那怎么判断一个视频的字幕是内嵌到帧上面的，而不是字幕文本。有没有样例的视频可以发一下？感激不尽

**Comment by fjqingyou** [comment]
@rumosky 播放的视频中，鼠标右键->字幕->选择字幕。。在弹出的列表中观察有没有字幕文件。例如：.ass。.ssa或者有可能是直接是文件名之类的。。如果没有一般就是硬绘制在画面中的。它们的位置一般是在‘依次选择字幕’、不显示‘ 这两个菜单的同级方框里面’

**Comment by rumosky** [comment]
@fjqingyou 好的，感谢，看来还是只能翻译外挂字幕视频。

**Comment by fjqingyou** [comment]
@rumosky 内封字幕也是支持的。有些字幕是直接跟视频打包在一起。但是又不是硬绘制的那种是支持的

**Comment by rumosky** [comment]
@fjqingyou OK
