### ISSUE TITLE
您好，请问能否添加一个当字幕有翻译时不进行翻译的功能呢？

### ISSUE THREAD

**Issue by squanbo** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#18]
我想的解决方案是在获取本行字幕的同时获取下一行字幕，如果本行字幕的翻译语言和下一行字幕的语言相同，那么跳过本行的翻译，因为默认翻译后的字幕都在源字幕的下一行。本人刚开始学习c，没找到获取源字幕的代码（太菜了），只找到判断是否输出翻译的代码，所以不会修改，请问可以实现吗，谢谢！

**Comment by fjqingyou** [comment]
并不需要那么麻烦，播放器本身自带识别原始语言的功能，可以设置为只有在源字幕是特定语言时才翻译的！播放器字幕翻译相关设置里面找找就有了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: squanbo <notifications@github.com&gt;
发送时间: 2021年3月4日 11:10
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu <PotPlayer_Subtitle_Translate_Baidu@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 您好，请问能否添加一个当字幕有翻译时不进行翻译的功能呢？ (#18)





 
我想的解决方案是在获取本行字幕的同时获取下一行字幕，如果本行字幕的翻译语言和下一行字幕的语言相同，那么跳过本行的翻译，因为默认翻译后的字幕都在源字幕的下一行。本人刚开始学习c，没找到获取源字幕的代码（太菜了），只找到判断是否输出翻译的代码，所以不会修改，请问可以实现吗，谢谢！

**Comment by squanbo** [comment]
嗯嗯，我知道这个功能，但是在设置自定义语言的时候，不管些什么格式的语言（比如 英语/English/en）都不能正确的识别，只能通过修改下方的原始语言来进行设置，请问那个自定义语言的格式怎么写啊，谢谢！（这也是自从我开始使用这个功能以来每一没有搞懂的东西）

**Comment by squanbo** [comment]
而且我又试了一下，就算设置了原始语言，在有翻译的情况下，还是会将原文翻译一遍显示在字幕自带的翻译下面，只是中文不会再翻译一遍而已，和脚本中的判断是否需要翻译的功能一样（或许就是脚本中的判断功能在起作用）

**Comment by squanbo** [comment]
就算是播放器自带的仅翻译英语，在原文有翻译的情况下还是会再翻译一遍，导致出现两行中文字幕，和不进行设置，只使用脚本的判断翻译是否有用的功能效果一样。

**Comment by squanbo** [comment]
![image](https://user-images.githubusercontent.com/59113362/109981607-088e8600-7d3c-11eb-9d4b-bf7622245b88.png)
效果如图

**Comment by squanbo** [comment]
您好，我刚才通过一些对字幕的修改，可以做到语言检测了，现在唯一的问题就是这个 仅用于目标语言 里面 自定义语言 的格式不会写，在网上也没有相关的例子，试了好几种都不行，请问如何填写呢？（麻烦您举个例子就行，英语已经正常运行了，但是不知道其他语言怎么填写）谢谢！

**Comment by squanbo** [comment]
您好，我现在有了新的解决方案，我在有翻译的字幕中都添加了"《 B R 》"（换行符），所以现在剩下的问题就是进行一个判断，在text（原文）中寻找"《BR》"，如果找到返回1否则返回负数，我阅读了angelscript的开发者文档，但是仍不会编写，报函数错误（太菜了），请问该如何编写呢？谢谢！（用中文 《 的原因是github会把《BR》识别成换行符）

**Comment by fjqingyou** [comment]
字符串是 potplaty 自己封装的
并不确定它提供了啥方法。。
不过字符串本质是连续一串字符串长度+\0结尾的内存。

所以
```
         //字符串[索引偏移] == 目标字符
        string strTest = "abcdefg";
        //strTest[0] == "a"[0] 
        //strTest[2] == "c"[0]
````

有必要的话，完全可以自己封装一个 strstr 的函数实现你的功能

**Comment by squanbo** [comment]
好的，我自己在里面添加了几行代码，添加在了Translate的函数下面，编译通过了，但是没有实现相应的功能，能请您帮忙看看吗？谢谢！
![image](https://user-images.githubusercontent.com/59113362/110190576-f0635780-7e5e-11eb-9b98-e97d26cf3d5d.png)
![image](https://user-images.githubusercontent.com/59113362/110190581-f48f7500-7e5e-11eb-8e61-cbbe282d6158.png)

string strTest="<BR>";
	for(int i = 0;i < srcLang.length();i++){
		if(text[i] == strTest[0]){
			if(text[i+1] == strTest[1]){
				if(text[i+2] == strTest[2]){
					ret = " ";
				}
else{ }
			}
else{ }
		}
else{ }
	}

**Comment by fjqingyou** [comment]
第一，else是多余的，建议先看看if else的语法。


第二，ret之后可以直接break了。没必要继续循环了，


第三，ret返回空字符串没意义，应该返回i才对，i才是索引，才是动态可变的！


第四，代码开始走打开控制台输出的代码我注释掉的，对于for debug注释下面的代码建议逐个解除注释了解下它们的作用！

**Comment by fjqingyou** [comment]
而且要查找的字符不应该是不是四个？才3
个if不够吧

**Comment by squanbo** [comment]
好的，我明白了，我已经在c的编译器里测试过新改的代码了，但是在脚本里，一直报这个错误
![image](https://user-images.githubusercontent.com/59113362/110194358-29a5c280-7e73-11eb-8f72-39c1a185befa.png)
我觉得是没有包含头文件造成的，但是，头文件写在哪林，哪里就报错'Unexpected token '<unrecognized token>'
请问如何修改呢？谢谢！

**Comment by squanbo** [comment]
char b[4]="<BR>";
	int i;
	for(i = 0;i < srcLang.length();i++){
		if(text[i] == b[0]){
			if(text[i+1] == b[1]){
				if(text[i+2] == b[2]){
					if(text[i+3] == b[3]){
					ret = " ";
					break;	
					}
				}
			}
		}
	}
这是修改后的代码，ret返回空值是因为您下面标注了这句话的作用
![image](https://user-images.githubusercontent.com/59113362/110194512-84d7b500-7e73-11eb-8ab9-247fdfc5497f.png)所以才这样子用的，谢谢!

**Comment by squanbo** [comment]
![image](https://user-images.githubusercontent.com/59113362/110194565-c6686000-7e73-11eb-8151-ba8fd3d49b9d.png)
![image](https://user-images.githubusercontent.com/59113362/110194566-c7998d00-7e73-11eb-8e7c-6a6cddc372d5.png)
这是在dev中跑成功的代码

**Comment by fjqingyou** [comment]
截图没提到的报错信息，唯有分号，b变量重复定义的错误

不建议c在vs里面写，因为不使用include编译指令，一些内置c函数vs能跑，potplayer不能跑。

**Comment by squanbo** [comment]
嗯嗯。。发现了。。但是b没有重复定义，也没少 ; 。我换了一个变量，也是报同样的错误，只有第一版是没有任何报错的。。

**Comment by squanbo** [comment]
我看您上面用string定义字符串，但是我没有用过，之前是复制过来改的，所以也不知道具体的作用。。

**Comment by fjqingyou** [comment]
报错不一定是提示刚，也许在上面也可能，可大批量临时注释掉代码，运行测试，逐个解除注释方时定位问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: squanbo <notifications@github.com&gt;
发送时间: 2021年3月6日 12:17
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu <PotPlayer_Subtitle_Translate_Baidu@noreply.github.com&gt;
抄送: FuLong <549773409@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 您好，请问能否添加一个当字幕有翻译时不进行翻译的功能呢？ (#18)





 
嗯嗯。。发现了。。但是b没有重复定义，也没少 ; 。我换了一个变量，也是报同样的错误，只有第一版是没有任何报错的。。

**Comment by fjqingyou** [comment]
这是potplayer内置的类型，我也没找到它的文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: squanbo <notifications@github.com&gt;
发送时间: 2021年3月6日 12:19
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu <PotPlayer_Subtitle_Translate_Baidu@noreply.github.com&gt;
抄送: FuLong <549773409@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 您好，请问能否添加一个当字幕有翻译时不进行翻译的功能呢？ (#18)





 
我看您上面用string定义字符串，但是我没有用过，之前是复制过来改的，所以也不知道具体的作用。。

**Comment by squanbo** [comment]
我这样修改了一下，不报错了，但是功能还是没有实现。。还是会再翻译一遍`
        string Translatetest1="<BR>";
	int i;
	for(i = 0;i < srcLang.length();i++){
		if(text[i] == Translatetest1[0]){
			if(text[i+1] == Translatetest1[1]){
				if(text[i+2] == Translatetest1[2]){
					if(text[i+3] == Translatetest1[3]){
					ret = " ";
					break;	
					}
				}
			}
		}
	}`

**Comment by squanbo** [comment]
我这样修改了一下，不报错了，但是功能还是没有实现。。还是会再翻译一遍
        string Translatetest1="<BR>";
	int i;
	for(i = 0;i < srcLang.length();i++){
		if(text[i] == Translatetest1[0]){
			if(text[i+1] == Translatetest1[1]){
				if(text[i+2] == Translatetest1[2]){
					if(text[i+3] == Translatetest1[3]){
					ret = " ";
					break;	
					}
				}
			}
		}
	}

**Comment by squanbo** [comment]
而且同样的代码在英文字幕中就可以发挥作用但是日语环境就不行
![image](https://user-images.githubusercontent.com/59113362/110195456-147f6280-7e78-11eb-8b0d-cff3e6cae59f.png)
![image](https://user-images.githubusercontent.com/59113362/110195457-15b08f80-7e78-11eb-814a-0eddf6a4b371.png)

**Comment by fjqingyou** [comment]
以翻译函数最终return的内容为准，建议return前一行打印它的内容以及长度到控制台观察



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: squanbo <notifications@github.com&gt;
发送时间: 2021年3月6日 12:25
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu <PotPlayer_Subtitle_Translate_Baidu@noreply.github.com&gt;
抄送: FuLong <549773409@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 您好，请问能否添加一个当字幕有翻译时不进行翻译的功能呢？ (#18)





 
我这样修改了一下，不报错了，但是功能还是没有实现。。还是会再翻译一遍
 string Translatetest1="
";
 int i;
 for(i = 0;i < srcLang.length();i++){
 if(text[i] == Translatetest1[0]){
 if(text[i+1] == Translatetest1[1]){
 if(text[i+2] == Translatetest1[2]){
 if(text[i+3] == Translatetest1[3]){
 ret = " ";
 break;
 }
 }
 }
 }
 }

**Comment by fjqingyou** [comment]
因为没识别出来源语言，不确定字幕文件是否支持主动告诉播放器自身语言，实在不行还可以把日语五十音图，浊音，拗音录入一个字符串。翻译时检查完翻译的字幕是否包含这个里面任意一个字符，有包含则说明肯定是日语！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: squanbo <notifications@github.com&gt;
发送时间: 2021年3月6日 12:33
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu <PotPlayer_Subtitle_Translate_Baidu@noreply.github.com&gt;
抄送: FuLong <549773409@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 您好，请问能否添加一个当字幕有翻译时不进行翻译的功能呢？ (#18)





 
而且同样的代码在英文字幕中就可以发挥作用但是日语环境就不行
