### ISSUE TITLE
正在编写脚本请教

### ISSUE THREAD

**Issue by Relax-87** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#19]
我正在参考您的as文件 尝试编写一个其他的功能，但是我发现无论如何我如何修改都无法加载到potplayer
这个anglescript 的as文件 是需要专用工具生成编写 c++代码然后编译生成码？
还是我直接可以使用您的 as文件直接做修改编写？
对于这类脚本初次接触还望指点！

**Comment by fjqingyou** [comment]
如果代码报错，例如语法错误就不会显示在列表中，可打开控制台确认。代码中有打开控制台的代码，被注释掉的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tosslog-admin ***@***.***&gt;
发送时间: 2021年8月1日 18:25
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 正在编写脚本请教 (#19)





 
我正在参考您的as文件 尝试编写一个其他的功能，但是我发现无论如何我如何修改都无法加载到potplayer
 这个anglescript 的as文件 是需要专用工具生成编写 c++代码然后编译生成码？
 还是我直接可以使用您的 as文件直接做修改编写？
 对于这类脚本初次接触还望指点！

**Comment by Relax-87** [comment]
首先非常感谢您的回复！  那么这个as 是否需要C++ 环境重新编译呢？ 还是我直接可以利用您的as脚本直接修改？ 

> 如果代码报错，例如语法错误就不会显示在列表中，可打开控制台确认。代码中有打开控制台的代码，被注释掉的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Tosslog-admin ***@***.***&gt; 发送时间: 2021年8月1日 18:25 收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 正在编写脚本请教 (#19) 我正在参考您的as文件 尝试编写一个其他的功能，但是我发现无论如何我如何修改都无法加载到potplayer 这个anglescript 的as文件 是需要专用工具生成编写 c++代码然后编译生成码？ 还是我直接可以使用您的 as文件直接做修改编写？ 对于这类脚本初次接触还望指点！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Relax-87** [comment]
再次感谢您的指点 我已经可以开始编写！祝您一帆风顺，一生平安！

> 如果代码报错，例如语法错误就不会显示在列表中，可打开控制台确认。代码中有打开控制台的代码，被注释掉的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Tosslog-admin ***@***.***&gt; 发送时间: 2021年8月1日 18:25 收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 正在编写脚本请教 (#19) 我正在参考您的as文件 尝试编写一个其他的功能，但是我发现无论如何我如何修改都无法加载到potplayer 这个anglescript 的as文件 是需要专用工具生成编写 c++代码然后编译生成码？ 还是我直接可以使用您的 as文件直接做修改编写？ 对于这类脚本初次接触还望指点！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
