### ISSUE TITLE
建议加入两个或者三个翻译平台一起显示结果

### ISSUE THREAD

**Issue by monywoex** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#2]
开发者你好,今天用了你发开的插件,非常感谢你的工作.

我个人在使用上有一个建议不知道是否能够实现.

如在chrome和firefox浏览器里有一款较多沙拉查词的扩展,就是同时向百度,有道,腾讯,等多个平台请求翻译结果,同时呈现翻译结果.

建议本插件是否也可以同时向多个翻译平台申请翻译,然后将翻译结果同时展现,以达到校正翻译结果的目的?

**Comment by fjqingyou** [comment]
集成多个平台是请求翻译结果。到这一步是可行的，不过存在一个问题。。我们要使用的字幕仅仅只要一个。不可能同时显示多个，不然会乱的

**Comment by fjqingyou** [comment]
@monywoex 如果没有对此的解决方案的话。暂时还没法做！

**Comment by monywoex** [comment]
> 
> 
> @monywoex 如果没有对此的解决方案的话。暂时还没法做！

**Comment by monywoex** [comment]
> 
> 
> 集成多个平台是请求翻译结果。到这一步是可行的，不过存在一个问题。。我们要使用的字幕仅仅只要一个。不可能同时显示多个，不然会乱的

确实如果同时显示多个,可能会乱,最初我的想法是
可能利用文字区分不同平台的结果
B:记者可以客观，无论是在电影中还是在印刷中
Y:无论是在电影中还是在出版物中，记者能做到客观吗
        Can a reporter be objective,be it in film or in print

**Comment by fjqingyou** [comment]
字幕中可能存在一次显示就是多行的情况，例如同时两个角色在说话。
假设是2行，那么加上翻译后的结果就是4行。
如果翻译来源是同时多个翻译平台，那么整个屏幕可能会大部分被翻译结果占据填充！
所以同时显示多个翻译结果，不太合适。。

而如果仅仅是为了可以选择翻译平台的话。我觉得PotPlayer做好的接口已经完全满足需求了。

![QQ拼音截图20190622210046](https://user-images.githubusercontent.com/31087168/59964317-bee31500-9531-11e9-9f5a-9e8287edf447.png)


![QQ拼音截图20190622210103](https://user-images.githubusercontent.com/31087168/59964322-c86c7d00-9531-11e9-8a5d-914cea576300.png)

当然，如果您有更好的建议？

**Comment by monywoex** [comment]
明白了,感谢大大的回复.之前考虑不周.想得太简单呢.

**Comment by fjqingyou** [comment]
不客气，那么我关闭这个 issue ，如果有关于这个话题的新想法，随时可以重新开启它！

**Comment by zl-bti** [comment]
大佬  非常感谢你的插件  超级好用  但是最近我因为电脑系统坏了 重新在装上就用不了了   不知道为什么  求帮助
