### ISSUE TITLE
您好朋友 请问 HostLoadLibrary 你调用成功了吗？

### ISSUE THREAD

**Issue by Relax-87** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#20]
我正打算向调用一下 HostLoadLibrary 函数来加载外部 dll动态库 
我看您在注释中有写到没有成功调用
不知道您最近有没有再次尝试过

**Comment by fjqingyou** [comment]
放脚本同文件夹的dll可以成功，不能用系统的！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tosslog-admin ***@***.***&gt;
发送时间: 2021年8月3日 00:41
收件人: fjqingyou/PotPlayer_Subtitle_Translate_Baidu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 您好朋友 请问 HostLoadLibrary 你调用成功了吗？ (#20)





 
我正打算向调用一下 HostLoadLibrary 函数来加载外部 dll动态库
 我看您在注释中有写到没有成功调用
 不知道您最近有没有再次尝试过

**Comment by Relax-87** [comment]
我将vc6.0的动态链接库dll 放在了 Extension\Media\PlayParse 目录下
在但是仍然没有任何其他输出
HostOpenConsole()开启后
其他代码正常输出但只有HostLoadLibrary
调用dll没有任何执行动向

下面是我的 dll 代码 与 potplayer as脚本调用代码
``` c++
#include <stdio.h>
int main(void)
{
	return 0;
}
extern "C" __declspec(dllexport) void Prt()
{
	WinExec("ipconfig",1);
}
```
``` angelscript

	uintptr dll =  HostLoadLibrary("test3.dll");
	HostPrintUTF8(""+dll);// 输0

	//
	uintptr fun = HostGetProcAddress(dll,"Prt");
	HostPrintUTF8(""+dll); //输出了0

	HostFreeLibrary(fun);
```

**Comment by Relax-87** [comment]
我已经成功使用 HostLoadLibrary 并且正常输出！感谢！
