### ISSUE TITLE
error: 54001, error_msg=Invalid Sign

### ISSUE THREAD

**Issue by lingfeixue** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#21]
这个要怎么解决？

**Comment by fjqingyou** [comment]
我这边实际测试正常翻译

请确认下AppId和密钥。

如果直接从网页复制过来可能会在前后存在不是内容的空格或者某个字符没完整复制到等。

如果是手动输入可能大小写输入错误后缀字母l和数字1，字母O和数字0输入错误等。

建议先开一个 notepad 的记事本程序，先从网页中复制到记事本，之后再复制到输入框中，以确保完整性。

**Comment by fjqingyou** [comment]
我这边实际测试正常翻译

请确认下AppId和密钥。

如果直接从网页复制过来可能会在前后存在不是内容的空格或者某个字符没完整复制到等。

如果是手动输入可能大小写输入错误后缀字母l和数字1，字母O和数字0输入错误等。

建议先开一个 notepad 的记事本程序，先从网页中复制到记事本，之后再复制到输入框中，以确保完整性。

**Comment by fjqingyou** [comment]
因为太久没回复，所以关闭这个 issues。

如果问题确实还存在随时可重新打开！
