### ISSUE TITLE
一测试你这个百度翻译就造成potplayer无响应

### ISSUE THREAD

**Issue by RallyQ** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#22]
之前你这个翻译好使来着，观看没有中文字幕仅有英文字幕的很方便，先感谢作者！！
后来某一天发现百度翻译无效了，而腾讯和谷歌正常，以为我百度翻译api问题，去百度官网查看，api正常有效中。
后发现在实时字幕翻译界面，选择百度翻译，无论是否输入我百度翻译帐号，点下面的测试，都会造成potplayer无响应，只能强制结束pot进程。pot新版旧版都试过，都是同样问题。但是腾讯和谷歌翻译都正常，很奇怪的现象
查看联网信息，点测试后腾讯和谷歌翻译都有联网动作，而百度翻译根本就没有联网动作pot就无响应了
麻烦作者帮忙分析一下到底是什么原因造成的？
删除卸载过pot的注册表和目录，反复测试，始终都是相同问题。你这个旧版新版插件也试过。
win10 21H1

**Comment by fjqingyou** [comment]
我这边测试正常工作
我的环境是：
系统：Windows 10 家庭中文版 21H2  -这个应该是一致的版本
Potplayer：210219(1.7.21422)  -可能是这个版本跟你不同，你是哪个版本？我这里试试？

**Comment by RallyQ** [comment]
> 我这边测试正常工作 我的环境是： 系统：Windows 10 家庭中文版 21H2 -这个应该是一致的版本 Potplayer：210219(1.7.21422) -可能是这个版本跟你不同，你是哪个版本？我这里试试？

1.7.21126和1.7.21566都试过

**Comment by RallyQ** [comment]
突然发现，百度翻译正常了，今天win10系统从休眠恢复时蓝屏死机，重启过系统。
看来是我系统原因，平常都不关机，都是休眠，可能长时间不重启，系统紊乱造成的。
就不用麻烦你测试了:-)
