### ISSUE TITLE
请问，error:58000，error_msg=INVALID_CLIENT_IP该怎么解决

### ISSUE THREAD

**Issue by S6bb** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#25]
请问，error:58000，error_msg=INVALID_CLIENT_IP该怎么解决，我查看过ip地址了，没有问题

**Comment by fjqingyou** [comment]
这个是你在百度翻译那边设置的ip限制导致的。
解决方案两种
1、从百度翻译那边删除掉 ip 地址限制，即不对任何ip进行限制（它的意思是：只允许某个ip发起，不是那个ip的禁止翻译，不填写则是无限制）
2、填写的ip地址必须是外网的ip，例如百度搜索 ip 两个字，会出自己ip地址，要填写的是那个(需要注意的是：这个方式，如果宽带不是固定ip，每次重启猫、路由器都可能导致这个ip地址发生变化，简单说重新拨号后就可能发生变化)

**Comment by S6bb** [comment]
谢谢，已解决
