### ISSUE TITLE
as脚本询问

### ISSUE THREAD

**Issue by cloudsmithy** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#28]
请问这个插件语言是actionscript嘛？求问这个开发的时候需要怎么调试呀？

**Comment by fjqingyou** [comment]
语言：AngelScript
调试：控制台输出内容，从内容判定是否符合预期。暂无动态调试支持

**Comment by cloudsmithy** [comment]
我发现这个语言还挺小众，我现在是在播放器中弄，每次更改都要重启播放器。这个能搭本地环境吗？

另外我在翻译得到时候经常出现，这个错误：The script was aborted before it could finish. Probably it timed out.

还想请教下是什么原因导致的

**Comment by fjqingyou** [comment]
如果是实时字幕翻译，只要停留在**实时翻译对话框**界面中，在脚本修改完毕后点击**再次搜索**按钮即可刷新。
重新搭建本地环境反而更麻烦，因为貌似并未有提供对应的IDE。
而错误的话，我是并未遇到过这个错误，并不知道为什么导致，看错误消息的翻译，是网络请求超时了？还是脚本执行时间超时了？

**Comment by cloudsmithy** [comment]
我是自己写的api，而且部署在本地，所以不太会是网络延迟，而且出现这个报错之后我用postman手动调用api 是正常的。

而且在potplayer的debug console [上多敲几下回车，然后似乎有所缓解，不太明白是什么原因。](url)

您这边有空可以玩玩我的这个：

https://github.com/mengze-han/potplayer_translate_plug_in
