### ISSUE TITLE
大佬能根据彩云小译的api, 做个potplayer字幕翻译插件吗....

### ISSUE THREAD

**Issue by seset** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#29]
创建 bash 脚本，xiaoyi.sh:
#!/bin/bash
tee xiaoyi.sh << END
DIRECTION=\$1
SOURCE=\$2
 
if test -f \$HOME/.xiaoyi ; then
  . \$HOME/.xiaoyi
fi
 
BODY='{"source": ["'\$SOURCE'"], "trans_type": "'\$DIRECTION'", "replaced": true, "media": "text", "request_id": "demo" }'
 
export PYTHONIOENCODING=utf8
curl -s -X POST http://api.interpreter.caiyunai.com/v1/translator\
      -H 'Content-Type: application/json'\
      -H "X-Authorization: token 填自己的token"\
      -d "\$BODY" | python -c "import sys, json; print json.load(sys.stdin)['target'][0]"
END
输入您想要翻译的英文句子并运行以下指令:
sh xiaoyi.sh en2zh "The sentence you want to translate."

创建 python 脚本:
import requests
import json
 
url = "http://api.interpreter.caiyunai.com/v1/translator"
 
token = "填自己的token"
 
payload = {
        "source" : ["Lingocloud is the best translation service.", 
                     "ColorfulClouds Weather is the best weather service."], 
        "trans_type" : "en2zh",
        "request_id" : "demo",
        }
 
headers = {
        'content-type': "application/json",
        'x-authorization': "token " + token,
}
 
response = requests.request("POST", url, data=json.dumps(payload), headers=headers)
 
print(response.text)
print(json.loads(response.text)['target'][0])
print(json.loads(response.text)['target'][1])
输出:
{"confidence":0.8,"target":["\u5f69\u4e91\u5c0f\u8bd1\u662f\u6700\u597d\u7684\u7ffb\u8bd1\u670d\u52a1\u3002",
"\u5f69\u4e91\u5929\u6c14\u662f\u6700\u597d\u7684\u6c14\u8c61\u670d\u52a1\u3002"],"rc":0}
 
彩云小译是最好的翻译服务。
彩云天气是最好的气象服务。

**Comment by fjqingyou** [comment]
我稍微看了下对方的文档描述，似乎并没有永久免费的方案呢。
```
新用户注册会获得100万字的免费翻译额度,有效期一个月；如果您使用超过100万字,我们会按照39元/100万字的费率收费。(字数按照翻译原文字符计算,包含空格和标点)
```

**Comment by fjqingyou** [comment]
因无免费方案，暂不考虑为这个做插件
