### ISSUE TITLE
From 2019.7.2 baidu change it's translate api servise, I cannot use it anymore?

### ISSUE THREAD

**Issue by FlotingDream** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#3]
potplayer x64
1.7.18346

**Comment by fjqingyou** [comment]
@FlotingDream 

Hello, My English is very bad, Sorry!

thank you!

yes, it work fail, Let me see it tomorrow. now I'm local time 2019-7-13 00:08:57, is too night!

**Comment by fjqingyou** [comment]
@FlotingDream 
I local test, it work normal, so i closed this issue.
If your execution is abnormal, please reopen this problem

**Comment by fjqingyou** [comment]
update code and reset config please
