### ISSUE TITLE
无法使用，点击测试出现xxx

### ISSUE THREAD

**Issue by L134139** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#35]
![1](https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu/assets/51356527/3d5e25c9-bc50-4390-8654-e348dc166fe9)
无法使用，点击测试出现xxx

**Comment by fjqingyou** [comment]
目标语言是指将当前内容翻译为谁。
因为原始中文简体，目标也是中文简体。为了不相同内容显示两遍。所以会自动抹除相同的结果。导致为空。
这个符合预期结果。

**Comment by L134139** [comment]
视频内容是中文语言，没有字幕，点百度翻译没有字幕出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月28日(周三) 晚上11:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fjqingyou/PotPlayer_Subtitle_Translate_Baidu] 无法使用，点击测试出现xxx (Issue #35)




 
目标语言是指将当前内容翻译为谁。
 因为原始中文简体，目标也是中文简体。为了不相同内容显示两遍。所以会自动抹除相同的结果。导致为空。
 这个符合预期结果。

**Comment by fjqingyou** [comment]
![image](https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu/assets/31087168/8000dcf2-7bab-4f55-a607-b08bcf72e787)

点击测试时，是按照这里输入的内容进行测试的。而这个例子中，输入都是中文，而且翻译的目标也是中文。所以进入了相同内容后忽略翻译结果的流程

**Comment by fjqingyou** [comment]
没有字幕的话是没法翻译的。这个插件是在现有字幕不是母语时，自动翻译为母语用的！例如 mkv 视频中的字幕是英文，用这个插件动态将现有的英文字幕翻译为中文。类似这样的作用！

**Comment by RustyYi** [comment]
佬 现在用自带的测试文本也显示空白该怎么办呢
![)%O@@{BUO85 ML9YU`T1W1E](https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu/assets/87636528/fe0262d7-dfb8-4803-8d3a-6545ab3ad43a)

**Comment by fjqingyou** [comment]
我测试了下两个例子：

## 例子一：
指定了 原始语言 + 目标语言 时。结果可行
![image](https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu/assets/31087168/5b31a13d-625e-4045-a0e5-070a6c5ce700)

## 例子二：
随意修改一下测试内容（相同内容只能测试一次）
然后原始语言自动检查， 而目标语言为测试语言中不包含的语言。例如下面这个例子中，测试内容是包含中文和英文。那么翻译为其他语言，例如这个例子中的日语。也是成功！
![image](https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu/assets/31087168/bf7775ec-00be-4132-bc62-d377190da211)

## 初步结论
看来原始语言是自动、而目标语言在要翻译的内容包含时。百度那边似乎会无法正常翻译！

而要处理这个问题的话会比较棘手，因为变成了插件需要识别内容是什么语言的功能支持，而这种功能放在插件中并不合适
