### ISSUE TITLE
对一些专业术语的翻译结果是不对的 我想对这类字幕进行再处理 怎么办呢？

### ISSUE THREAD

**Issue by iou3344** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#36]
目前的机制是取回翻译引擎的翻译结果A，并呈现出来双语字幕。唯一可以去影响翻译结果的机会就在取回翻译引擎的翻译结果A但又没用呈现出来之前的这段缝隙时间内，将翻译结果A替换成翻译结果B，再呈现出来当前时间轴的双语字幕。我感觉时间是够的，因为从A-B的替换过程会很快，而且不是每一句字幕都需要替换。但具体怎么修改你的代码呢？

**Comment by iou3344** [comment]
一对多的随机替换还没有解决，原因是在AngelScript环境下不会生成随机数，难死我了。。。

**Comment by fjqingyou** [comment]
关于第一条，我不确定你是遇到了什么问题需要解决。
关于第二条，随机数一般都是伪随机，例如当前时间戳等等的一些外在可变数据作为随机种子计算。完全可以封装一个函数去实现随机逻辑
