### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zl-bti** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#5]
感谢大大的插件 ，之前挺好用的  后来我重新安装了一次软件 现在出了点问题 安装插件后测试提示是支持在线翻译的  但是实际上是翻译不了的  求帮助

**Comment by fjqingyou** [comment]
感谢提交问题。
不过我这里是正常工作的，所以您的翻译设置上可能存在问题，[请点击这里阅读下 readme.md 文件](../blob/master/readme.md) 看看是否有哪个步骤没做。为确保正常工作，请重新全部确认一遍！

**Comment by fjqingyou** [comment]
太久没回复，我关闭这个问题了，如果有新的进展可以重新打开这个问题
