### ISSUE TITLE
您好，请问错误 58003 是什么？如何解决？谢谢！

### ISSUE THREAD

**Issue by squanbo** [fjqingyou/PotPlayer_Subtitle_Translate_Baidu#6]
今天使用的时候出现error：58003 error_msg=service invalid 以前未出现过，错误对照表里也没有，请问如何解决，谢谢！

**Comment by fjqingyou** [comment]
百度翻译官方文档中，没有对这个错误描述做出说明，所以我也不知道具体是什么，后来问了百度翻译的官方的机器人客服，给我下面的回答：

问题：通用翻译API提示58003错误，怎么办？

答案：如上所述，因黑产采用不正当手段收集用户APPID及密钥，由此产生的盗刷字符量现象日益猖獗，系统风控增加了IP校验规则，如同一IP当日使用多个APPID发送翻译请求，则该IP将被封禁当日请求权限，次日解封。

但由于IP多变，应用场景复杂，难免出现误伤正常使用的情况。如您属正常使用，但出现58003的提示，请发送邮件至 translate_api@baidu.com，同时提供如下信息。我方在收到邮件后将与您取得联系，核实后将解除封禁。

公司名称：
产品名称：
联系人：
联系方式：
服务器IP：
APPID：
注：如提供信息不全，将影响审核通过率。

**Comment by squanbo** [comment]
明白了，谢谢！但是我只使用potplayer来进行api的翻译，没使用过其它的软件，而且昨天挂了v以后翻译又突然能使用了，昨天不能使用，今天又可以使用了。。😅总之，谢谢！！

**Comment by fjqingyou** [comment]
估计是同一个局域网有多个人在使用不同的id吧。。
